// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/apis/inference.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tensorflow_5fserving_2fapis_2finference_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tensorflow_5fserving_2fapis_2finference_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow_serving/apis/classification.pb.h"
#include "tensorflow_serving/apis/input.pb.h"
#include "tensorflow_serving/apis/model.pb.h"
#include "tensorflow_serving/apis/regression.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tensorflow_5fserving_2fapis_2finference_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tensorflow_5fserving_2fapis_2finference_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tensorflow_5fserving_2fapis_2finference_2eproto;
namespace tensorflow {
namespace serving {
class InferenceResult;
struct InferenceResultDefaultTypeInternal;
extern InferenceResultDefaultTypeInternal _InferenceResult_default_instance_;
class InferenceTask;
struct InferenceTaskDefaultTypeInternal;
extern InferenceTaskDefaultTypeInternal _InferenceTask_default_instance_;
class MultiInferenceRequest;
struct MultiInferenceRequestDefaultTypeInternal;
extern MultiInferenceRequestDefaultTypeInternal _MultiInferenceRequest_default_instance_;
class MultiInferenceResponse;
struct MultiInferenceResponseDefaultTypeInternal;
extern MultiInferenceResponseDefaultTypeInternal _MultiInferenceResponse_default_instance_;
}  // namespace serving
}  // namespace tensorflow
PROTOBUF_NAMESPACE_OPEN
template<> ::tensorflow::serving::InferenceResult* Arena::CreateMaybeMessage<::tensorflow::serving::InferenceResult>(Arena*);
template<> ::tensorflow::serving::InferenceTask* Arena::CreateMaybeMessage<::tensorflow::serving::InferenceTask>(Arena*);
template<> ::tensorflow::serving::MultiInferenceRequest* Arena::CreateMaybeMessage<::tensorflow::serving::MultiInferenceRequest>(Arena*);
template<> ::tensorflow::serving::MultiInferenceResponse* Arena::CreateMaybeMessage<::tensorflow::serving::MultiInferenceResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tensorflow {
namespace serving {

// ===================================================================

class InferenceTask final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.InferenceTask) */ {
 public:
  inline InferenceTask() : InferenceTask(nullptr) {}
  ~InferenceTask() override;
  explicit PROTOBUF_CONSTEXPR InferenceTask(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InferenceTask(const InferenceTask& from);
  InferenceTask(InferenceTask&& from) noexcept
    : InferenceTask() {
    *this = ::std::move(from);
  }

  inline InferenceTask& operator=(const InferenceTask& from) {
    CopyFrom(from);
    return *this;
  }
  inline InferenceTask& operator=(InferenceTask&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InferenceTask& default_instance() {
    return *internal_default_instance();
  }
  static inline const InferenceTask* internal_default_instance() {
    return reinterpret_cast<const InferenceTask*>(
               &_InferenceTask_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InferenceTask& a, InferenceTask& b) {
    a.Swap(&b);
  }
  inline void Swap(InferenceTask* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InferenceTask* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InferenceTask* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InferenceTask>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InferenceTask& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InferenceTask& from) {
    InferenceTask::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InferenceTask* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tensorflow.serving.InferenceTask";
  }
  protected:
  explicit InferenceTask(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMethodNameFieldNumber = 2,
    kModelSpecFieldNumber = 1,
  };
  // string method_name = 2;
  void clear_method_name();
  const std::string& method_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_method_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_method_name();
  PROTOBUF_NODISCARD std::string* release_method_name();
  void set_allocated_method_name(std::string* method_name);
  private:
  const std::string& _internal_method_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_method_name(const std::string& value);
  std::string* _internal_mutable_method_name();
  public:

  // .tensorflow.serving.ModelSpec model_spec = 1;
  bool has_model_spec() const;
  private:
  bool _internal_has_model_spec() const;
  public:
  void clear_model_spec();
  const ::tensorflow::serving::ModelSpec& model_spec() const;
  PROTOBUF_NODISCARD ::tensorflow::serving::ModelSpec* release_model_spec();
  ::tensorflow::serving::ModelSpec* mutable_model_spec();
  void set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec);
  private:
  const ::tensorflow::serving::ModelSpec& _internal_model_spec() const;
  ::tensorflow::serving::ModelSpec* _internal_mutable_model_spec();
  public:
  void unsafe_arena_set_allocated_model_spec(
      ::tensorflow::serving::ModelSpec* model_spec);
  ::tensorflow::serving::ModelSpec* unsafe_arena_release_model_spec();

  // @@protoc_insertion_point(class_scope:tensorflow.serving.InferenceTask)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr method_name_;
    ::tensorflow::serving::ModelSpec* model_spec_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tensorflow_5fserving_2fapis_2finference_2eproto;
};
// -------------------------------------------------------------------

class InferenceResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.InferenceResult) */ {
 public:
  inline InferenceResult() : InferenceResult(nullptr) {}
  ~InferenceResult() override;
  explicit PROTOBUF_CONSTEXPR InferenceResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InferenceResult(const InferenceResult& from);
  InferenceResult(InferenceResult&& from) noexcept
    : InferenceResult() {
    *this = ::std::move(from);
  }

  inline InferenceResult& operator=(const InferenceResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline InferenceResult& operator=(InferenceResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InferenceResult& default_instance() {
    return *internal_default_instance();
  }
  enum ResultCase {
    kClassificationResult = 2,
    kRegressionResult = 3,
    RESULT_NOT_SET = 0,
  };

  static inline const InferenceResult* internal_default_instance() {
    return reinterpret_cast<const InferenceResult*>(
               &_InferenceResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(InferenceResult& a, InferenceResult& b) {
    a.Swap(&b);
  }
  inline void Swap(InferenceResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InferenceResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InferenceResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InferenceResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InferenceResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InferenceResult& from) {
    InferenceResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InferenceResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tensorflow.serving.InferenceResult";
  }
  protected:
  explicit InferenceResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModelSpecFieldNumber = 1,
    kClassificationResultFieldNumber = 2,
    kRegressionResultFieldNumber = 3,
  };
  // .tensorflow.serving.ModelSpec model_spec = 1;
  bool has_model_spec() const;
  private:
  bool _internal_has_model_spec() const;
  public:
  void clear_model_spec();
  const ::tensorflow::serving::ModelSpec& model_spec() const;
  PROTOBUF_NODISCARD ::tensorflow::serving::ModelSpec* release_model_spec();
  ::tensorflow::serving::ModelSpec* mutable_model_spec();
  void set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec);
  private:
  const ::tensorflow::serving::ModelSpec& _internal_model_spec() const;
  ::tensorflow::serving::ModelSpec* _internal_mutable_model_spec();
  public:
  void unsafe_arena_set_allocated_model_spec(
      ::tensorflow::serving::ModelSpec* model_spec);
  ::tensorflow::serving::ModelSpec* unsafe_arena_release_model_spec();

  // .tensorflow.serving.ClassificationResult classification_result = 2;
  bool has_classification_result() const;
  private:
  bool _internal_has_classification_result() const;
  public:
  void clear_classification_result();
  const ::tensorflow::serving::ClassificationResult& classification_result() const;
  PROTOBUF_NODISCARD ::tensorflow::serving::ClassificationResult* release_classification_result();
  ::tensorflow::serving::ClassificationResult* mutable_classification_result();
  void set_allocated_classification_result(::tensorflow::serving::ClassificationResult* classification_result);
  private:
  const ::tensorflow::serving::ClassificationResult& _internal_classification_result() const;
  ::tensorflow::serving::ClassificationResult* _internal_mutable_classification_result();
  public:
  void unsafe_arena_set_allocated_classification_result(
      ::tensorflow::serving::ClassificationResult* classification_result);
  ::tensorflow::serving::ClassificationResult* unsafe_arena_release_classification_result();

  // .tensorflow.serving.RegressionResult regression_result = 3;
  bool has_regression_result() const;
  private:
  bool _internal_has_regression_result() const;
  public:
  void clear_regression_result();
  const ::tensorflow::serving::RegressionResult& regression_result() const;
  PROTOBUF_NODISCARD ::tensorflow::serving::RegressionResult* release_regression_result();
  ::tensorflow::serving::RegressionResult* mutable_regression_result();
  void set_allocated_regression_result(::tensorflow::serving::RegressionResult* regression_result);
  private:
  const ::tensorflow::serving::RegressionResult& _internal_regression_result() const;
  ::tensorflow::serving::RegressionResult* _internal_mutable_regression_result();
  public:
  void unsafe_arena_set_allocated_regression_result(
      ::tensorflow::serving::RegressionResult* regression_result);
  ::tensorflow::serving::RegressionResult* unsafe_arena_release_regression_result();

  void clear_result();
  ResultCase result_case() const;
  // @@protoc_insertion_point(class_scope:tensorflow.serving.InferenceResult)
 private:
  class _Internal;
  void set_has_classification_result();
  void set_has_regression_result();

  inline bool has_result() const;
  inline void clear_has_result();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::tensorflow::serving::ModelSpec* model_spec_;
    union ResultUnion {
      constexpr ResultUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::tensorflow::serving::ClassificationResult* classification_result_;
      ::tensorflow::serving::RegressionResult* regression_result_;
    } result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tensorflow_5fserving_2fapis_2finference_2eproto;
};
// -------------------------------------------------------------------

class MultiInferenceRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.MultiInferenceRequest) */ {
 public:
  inline MultiInferenceRequest() : MultiInferenceRequest(nullptr) {}
  ~MultiInferenceRequest() override;
  explicit PROTOBUF_CONSTEXPR MultiInferenceRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MultiInferenceRequest(const MultiInferenceRequest& from);
  MultiInferenceRequest(MultiInferenceRequest&& from) noexcept
    : MultiInferenceRequest() {
    *this = ::std::move(from);
  }

  inline MultiInferenceRequest& operator=(const MultiInferenceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MultiInferenceRequest& operator=(MultiInferenceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MultiInferenceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const MultiInferenceRequest* internal_default_instance() {
    return reinterpret_cast<const MultiInferenceRequest*>(
               &_MultiInferenceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MultiInferenceRequest& a, MultiInferenceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(MultiInferenceRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MultiInferenceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MultiInferenceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MultiInferenceRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MultiInferenceRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MultiInferenceRequest& from) {
    MultiInferenceRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MultiInferenceRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tensorflow.serving.MultiInferenceRequest";
  }
  protected:
  explicit MultiInferenceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTasksFieldNumber = 1,
    kInputFieldNumber = 2,
  };
  // repeated .tensorflow.serving.InferenceTask tasks = 1;
  int tasks_size() const;
  private:
  int _internal_tasks_size() const;
  public:
  void clear_tasks();
  ::tensorflow::serving::InferenceTask* mutable_tasks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceTask >*
      mutable_tasks();
  private:
  const ::tensorflow::serving::InferenceTask& _internal_tasks(int index) const;
  ::tensorflow::serving::InferenceTask* _internal_add_tasks();
  public:
  const ::tensorflow::serving::InferenceTask& tasks(int index) const;
  ::tensorflow::serving::InferenceTask* add_tasks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceTask >&
      tasks() const;

  // .tensorflow.serving.Input input = 2;
  bool has_input() const;
  private:
  bool _internal_has_input() const;
  public:
  void clear_input();
  const ::tensorflow::serving::Input& input() const;
  PROTOBUF_NODISCARD ::tensorflow::serving::Input* release_input();
  ::tensorflow::serving::Input* mutable_input();
  void set_allocated_input(::tensorflow::serving::Input* input);
  private:
  const ::tensorflow::serving::Input& _internal_input() const;
  ::tensorflow::serving::Input* _internal_mutable_input();
  public:
  void unsafe_arena_set_allocated_input(
      ::tensorflow::serving::Input* input);
  ::tensorflow::serving::Input* unsafe_arena_release_input();

  // @@protoc_insertion_point(class_scope:tensorflow.serving.MultiInferenceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceTask > tasks_;
    ::tensorflow::serving::Input* input_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tensorflow_5fserving_2fapis_2finference_2eproto;
};
// -------------------------------------------------------------------

class MultiInferenceResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.MultiInferenceResponse) */ {
 public:
  inline MultiInferenceResponse() : MultiInferenceResponse(nullptr) {}
  ~MultiInferenceResponse() override;
  explicit PROTOBUF_CONSTEXPR MultiInferenceResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MultiInferenceResponse(const MultiInferenceResponse& from);
  MultiInferenceResponse(MultiInferenceResponse&& from) noexcept
    : MultiInferenceResponse() {
    *this = ::std::move(from);
  }

  inline MultiInferenceResponse& operator=(const MultiInferenceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline MultiInferenceResponse& operator=(MultiInferenceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MultiInferenceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const MultiInferenceResponse* internal_default_instance() {
    return reinterpret_cast<const MultiInferenceResponse*>(
               &_MultiInferenceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MultiInferenceResponse& a, MultiInferenceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(MultiInferenceResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MultiInferenceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MultiInferenceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MultiInferenceResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MultiInferenceResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MultiInferenceResponse& from) {
    MultiInferenceResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MultiInferenceResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tensorflow.serving.MultiInferenceResponse";
  }
  protected:
  explicit MultiInferenceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultsFieldNumber = 1,
  };
  // repeated .tensorflow.serving.InferenceResult results = 1;
  int results_size() const;
  private:
  int _internal_results_size() const;
  public:
  void clear_results();
  ::tensorflow::serving::InferenceResult* mutable_results(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceResult >*
      mutable_results();
  private:
  const ::tensorflow::serving::InferenceResult& _internal_results(int index) const;
  ::tensorflow::serving::InferenceResult* _internal_add_results();
  public:
  const ::tensorflow::serving::InferenceResult& results(int index) const;
  ::tensorflow::serving::InferenceResult* add_results();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceResult >&
      results() const;

  // @@protoc_insertion_point(class_scope:tensorflow.serving.MultiInferenceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceResult > results_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tensorflow_5fserving_2fapis_2finference_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InferenceTask

// .tensorflow.serving.ModelSpec model_spec = 1;
inline bool InferenceTask::_internal_has_model_spec() const {
  return this != internal_default_instance() && _impl_.model_spec_ != nullptr;
}
inline bool InferenceTask::has_model_spec() const {
  return _internal_has_model_spec();
}
inline const ::tensorflow::serving::ModelSpec& InferenceTask::_internal_model_spec() const {
  const ::tensorflow::serving::ModelSpec* p = _impl_.model_spec_;
  return p != nullptr ? *p : reinterpret_cast<const ::tensorflow::serving::ModelSpec&>(
      ::tensorflow::serving::_ModelSpec_default_instance_);
}
inline const ::tensorflow::serving::ModelSpec& InferenceTask::model_spec() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.InferenceTask.model_spec)
  return _internal_model_spec();
}
inline void InferenceTask::unsafe_arena_set_allocated_model_spec(
    ::tensorflow::serving::ModelSpec* model_spec) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_spec_);
  }
  _impl_.model_spec_ = model_spec;
  if (model_spec) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.InferenceTask.model_spec)
}
inline ::tensorflow::serving::ModelSpec* InferenceTask::release_model_spec() {
  
  ::tensorflow::serving::ModelSpec* temp = _impl_.model_spec_;
  _impl_.model_spec_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tensorflow::serving::ModelSpec* InferenceTask::unsafe_arena_release_model_spec() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.InferenceTask.model_spec)
  
  ::tensorflow::serving::ModelSpec* temp = _impl_.model_spec_;
  _impl_.model_spec_ = nullptr;
  return temp;
}
inline ::tensorflow::serving::ModelSpec* InferenceTask::_internal_mutable_model_spec() {
  
  if (_impl_.model_spec_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::serving::ModelSpec>(GetArenaForAllocation());
    _impl_.model_spec_ = p;
  }
  return _impl_.model_spec_;
}
inline ::tensorflow::serving::ModelSpec* InferenceTask::mutable_model_spec() {
  ::tensorflow::serving::ModelSpec* _msg = _internal_mutable_model_spec();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.InferenceTask.model_spec)
  return _msg;
}
inline void InferenceTask::set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_spec_);
  }
  if (model_spec) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(model_spec));
    if (message_arena != submessage_arena) {
      model_spec = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, model_spec, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.model_spec_ = model_spec;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.InferenceTask.model_spec)
}

// string method_name = 2;
inline void InferenceTask::clear_method_name() {
  _impl_.method_name_.ClearToEmpty();
}
inline const std::string& InferenceTask::method_name() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.InferenceTask.method_name)
  return _internal_method_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InferenceTask::set_method_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.method_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:tensorflow.serving.InferenceTask.method_name)
}
inline std::string* InferenceTask::mutable_method_name() {
  std::string* _s = _internal_mutable_method_name();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.InferenceTask.method_name)
  return _s;
}
inline const std::string& InferenceTask::_internal_method_name() const {
  return _impl_.method_name_.Get();
}
inline void InferenceTask::_internal_set_method_name(const std::string& value) {
  
  _impl_.method_name_.Set(value, GetArenaForAllocation());
}
inline std::string* InferenceTask::_internal_mutable_method_name() {
  
  return _impl_.method_name_.Mutable(GetArenaForAllocation());
}
inline std::string* InferenceTask::release_method_name() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.InferenceTask.method_name)
  return _impl_.method_name_.Release();
}
inline void InferenceTask::set_allocated_method_name(std::string* method_name) {
  if (method_name != nullptr) {
    
  } else {
    
  }
  _impl_.method_name_.SetAllocated(method_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.method_name_.IsDefault()) {
    _impl_.method_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.InferenceTask.method_name)
}

// -------------------------------------------------------------------

// InferenceResult

// .tensorflow.serving.ModelSpec model_spec = 1;
inline bool InferenceResult::_internal_has_model_spec() const {
  return this != internal_default_instance() && _impl_.model_spec_ != nullptr;
}
inline bool InferenceResult::has_model_spec() const {
  return _internal_has_model_spec();
}
inline const ::tensorflow::serving::ModelSpec& InferenceResult::_internal_model_spec() const {
  const ::tensorflow::serving::ModelSpec* p = _impl_.model_spec_;
  return p != nullptr ? *p : reinterpret_cast<const ::tensorflow::serving::ModelSpec&>(
      ::tensorflow::serving::_ModelSpec_default_instance_);
}
inline const ::tensorflow::serving::ModelSpec& InferenceResult::model_spec() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.InferenceResult.model_spec)
  return _internal_model_spec();
}
inline void InferenceResult::unsafe_arena_set_allocated_model_spec(
    ::tensorflow::serving::ModelSpec* model_spec) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_spec_);
  }
  _impl_.model_spec_ = model_spec;
  if (model_spec) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.InferenceResult.model_spec)
}
inline ::tensorflow::serving::ModelSpec* InferenceResult::release_model_spec() {
  
  ::tensorflow::serving::ModelSpec* temp = _impl_.model_spec_;
  _impl_.model_spec_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tensorflow::serving::ModelSpec* InferenceResult::unsafe_arena_release_model_spec() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.InferenceResult.model_spec)
  
  ::tensorflow::serving::ModelSpec* temp = _impl_.model_spec_;
  _impl_.model_spec_ = nullptr;
  return temp;
}
inline ::tensorflow::serving::ModelSpec* InferenceResult::_internal_mutable_model_spec() {
  
  if (_impl_.model_spec_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::serving::ModelSpec>(GetArenaForAllocation());
    _impl_.model_spec_ = p;
  }
  return _impl_.model_spec_;
}
inline ::tensorflow::serving::ModelSpec* InferenceResult::mutable_model_spec() {
  ::tensorflow::serving::ModelSpec* _msg = _internal_mutable_model_spec();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.InferenceResult.model_spec)
  return _msg;
}
inline void InferenceResult::set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_spec_);
  }
  if (model_spec) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(model_spec));
    if (message_arena != submessage_arena) {
      model_spec = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, model_spec, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.model_spec_ = model_spec;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.InferenceResult.model_spec)
}

// .tensorflow.serving.ClassificationResult classification_result = 2;
inline bool InferenceResult::_internal_has_classification_result() const {
  return result_case() == kClassificationResult;
}
inline bool InferenceResult::has_classification_result() const {
  return _internal_has_classification_result();
}
inline void InferenceResult::set_has_classification_result() {
  _impl_._oneof_case_[0] = kClassificationResult;
}
inline ::tensorflow::serving::ClassificationResult* InferenceResult::release_classification_result() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.InferenceResult.classification_result)
  if (_internal_has_classification_result()) {
    clear_has_result();
    ::tensorflow::serving::ClassificationResult* temp = _impl_.result_.classification_result_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.result_.classification_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::tensorflow::serving::ClassificationResult& InferenceResult::_internal_classification_result() const {
  return _internal_has_classification_result()
      ? *_impl_.result_.classification_result_
      : reinterpret_cast< ::tensorflow::serving::ClassificationResult&>(::tensorflow::serving::_ClassificationResult_default_instance_);
}
inline const ::tensorflow::serving::ClassificationResult& InferenceResult::classification_result() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.InferenceResult.classification_result)
  return _internal_classification_result();
}
inline ::tensorflow::serving::ClassificationResult* InferenceResult::unsafe_arena_release_classification_result() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.InferenceResult.classification_result)
  if (_internal_has_classification_result()) {
    clear_has_result();
    ::tensorflow::serving::ClassificationResult* temp = _impl_.result_.classification_result_;
    _impl_.result_.classification_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void InferenceResult::unsafe_arena_set_allocated_classification_result(::tensorflow::serving::ClassificationResult* classification_result) {
  clear_result();
  if (classification_result) {
    set_has_classification_result();
    _impl_.result_.classification_result_ = classification_result;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.InferenceResult.classification_result)
}
inline ::tensorflow::serving::ClassificationResult* InferenceResult::_internal_mutable_classification_result() {
  if (!_internal_has_classification_result()) {
    clear_result();
    set_has_classification_result();
    _impl_.result_.classification_result_ = CreateMaybeMessage< ::tensorflow::serving::ClassificationResult >(GetArenaForAllocation());
  }
  return _impl_.result_.classification_result_;
}
inline ::tensorflow::serving::ClassificationResult* InferenceResult::mutable_classification_result() {
  ::tensorflow::serving::ClassificationResult* _msg = _internal_mutable_classification_result();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.InferenceResult.classification_result)
  return _msg;
}

// .tensorflow.serving.RegressionResult regression_result = 3;
inline bool InferenceResult::_internal_has_regression_result() const {
  return result_case() == kRegressionResult;
}
inline bool InferenceResult::has_regression_result() const {
  return _internal_has_regression_result();
}
inline void InferenceResult::set_has_regression_result() {
  _impl_._oneof_case_[0] = kRegressionResult;
}
inline ::tensorflow::serving::RegressionResult* InferenceResult::release_regression_result() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.InferenceResult.regression_result)
  if (_internal_has_regression_result()) {
    clear_has_result();
    ::tensorflow::serving::RegressionResult* temp = _impl_.result_.regression_result_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.result_.regression_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::tensorflow::serving::RegressionResult& InferenceResult::_internal_regression_result() const {
  return _internal_has_regression_result()
      ? *_impl_.result_.regression_result_
      : reinterpret_cast< ::tensorflow::serving::RegressionResult&>(::tensorflow::serving::_RegressionResult_default_instance_);
}
inline const ::tensorflow::serving::RegressionResult& InferenceResult::regression_result() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.InferenceResult.regression_result)
  return _internal_regression_result();
}
inline ::tensorflow::serving::RegressionResult* InferenceResult::unsafe_arena_release_regression_result() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.InferenceResult.regression_result)
  if (_internal_has_regression_result()) {
    clear_has_result();
    ::tensorflow::serving::RegressionResult* temp = _impl_.result_.regression_result_;
    _impl_.result_.regression_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void InferenceResult::unsafe_arena_set_allocated_regression_result(::tensorflow::serving::RegressionResult* regression_result) {
  clear_result();
  if (regression_result) {
    set_has_regression_result();
    _impl_.result_.regression_result_ = regression_result;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.InferenceResult.regression_result)
}
inline ::tensorflow::serving::RegressionResult* InferenceResult::_internal_mutable_regression_result() {
  if (!_internal_has_regression_result()) {
    clear_result();
    set_has_regression_result();
    _impl_.result_.regression_result_ = CreateMaybeMessage< ::tensorflow::serving::RegressionResult >(GetArenaForAllocation());
  }
  return _impl_.result_.regression_result_;
}
inline ::tensorflow::serving::RegressionResult* InferenceResult::mutable_regression_result() {
  ::tensorflow::serving::RegressionResult* _msg = _internal_mutable_regression_result();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.InferenceResult.regression_result)
  return _msg;
}

inline bool InferenceResult::has_result() const {
  return result_case() != RESULT_NOT_SET;
}
inline void InferenceResult::clear_has_result() {
  _impl_._oneof_case_[0] = RESULT_NOT_SET;
}
inline InferenceResult::ResultCase InferenceResult::result_case() const {
  return InferenceResult::ResultCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// MultiInferenceRequest

// repeated .tensorflow.serving.InferenceTask tasks = 1;
inline int MultiInferenceRequest::_internal_tasks_size() const {
  return _impl_.tasks_.size();
}
inline int MultiInferenceRequest::tasks_size() const {
  return _internal_tasks_size();
}
inline void MultiInferenceRequest::clear_tasks() {
  _impl_.tasks_.Clear();
}
inline ::tensorflow::serving::InferenceTask* MultiInferenceRequest::mutable_tasks(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.MultiInferenceRequest.tasks)
  return _impl_.tasks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceTask >*
MultiInferenceRequest::mutable_tasks() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.MultiInferenceRequest.tasks)
  return &_impl_.tasks_;
}
inline const ::tensorflow::serving::InferenceTask& MultiInferenceRequest::_internal_tasks(int index) const {
  return _impl_.tasks_.Get(index);
}
inline const ::tensorflow::serving::InferenceTask& MultiInferenceRequest::tasks(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.MultiInferenceRequest.tasks)
  return _internal_tasks(index);
}
inline ::tensorflow::serving::InferenceTask* MultiInferenceRequest::_internal_add_tasks() {
  return _impl_.tasks_.Add();
}
inline ::tensorflow::serving::InferenceTask* MultiInferenceRequest::add_tasks() {
  ::tensorflow::serving::InferenceTask* _add = _internal_add_tasks();
  // @@protoc_insertion_point(field_add:tensorflow.serving.MultiInferenceRequest.tasks)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceTask >&
MultiInferenceRequest::tasks() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.MultiInferenceRequest.tasks)
  return _impl_.tasks_;
}

// .tensorflow.serving.Input input = 2;
inline bool MultiInferenceRequest::_internal_has_input() const {
  return this != internal_default_instance() && _impl_.input_ != nullptr;
}
inline bool MultiInferenceRequest::has_input() const {
  return _internal_has_input();
}
inline const ::tensorflow::serving::Input& MultiInferenceRequest::_internal_input() const {
  const ::tensorflow::serving::Input* p = _impl_.input_;
  return p != nullptr ? *p : reinterpret_cast<const ::tensorflow::serving::Input&>(
      ::tensorflow::serving::_Input_default_instance_);
}
inline const ::tensorflow::serving::Input& MultiInferenceRequest::input() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.MultiInferenceRequest.input)
  return _internal_input();
}
inline void MultiInferenceRequest::unsafe_arena_set_allocated_input(
    ::tensorflow::serving::Input* input) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.input_);
  }
  _impl_.input_ = input;
  if (input) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.MultiInferenceRequest.input)
}
inline ::tensorflow::serving::Input* MultiInferenceRequest::release_input() {
  
  ::tensorflow::serving::Input* temp = _impl_.input_;
  _impl_.input_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tensorflow::serving::Input* MultiInferenceRequest::unsafe_arena_release_input() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.MultiInferenceRequest.input)
  
  ::tensorflow::serving::Input* temp = _impl_.input_;
  _impl_.input_ = nullptr;
  return temp;
}
inline ::tensorflow::serving::Input* MultiInferenceRequest::_internal_mutable_input() {
  
  if (_impl_.input_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::serving::Input>(GetArenaForAllocation());
    _impl_.input_ = p;
  }
  return _impl_.input_;
}
inline ::tensorflow::serving::Input* MultiInferenceRequest::mutable_input() {
  ::tensorflow::serving::Input* _msg = _internal_mutable_input();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.MultiInferenceRequest.input)
  return _msg;
}
inline void MultiInferenceRequest::set_allocated_input(::tensorflow::serving::Input* input) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.input_);
  }
  if (input) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(input));
    if (message_arena != submessage_arena) {
      input = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, input, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.input_ = input;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.MultiInferenceRequest.input)
}

// -------------------------------------------------------------------

// MultiInferenceResponse

// repeated .tensorflow.serving.InferenceResult results = 1;
inline int MultiInferenceResponse::_internal_results_size() const {
  return _impl_.results_.size();
}
inline int MultiInferenceResponse::results_size() const {
  return _internal_results_size();
}
inline void MultiInferenceResponse::clear_results() {
  _impl_.results_.Clear();
}
inline ::tensorflow::serving::InferenceResult* MultiInferenceResponse::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.MultiInferenceResponse.results)
  return _impl_.results_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceResult >*
MultiInferenceResponse::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.MultiInferenceResponse.results)
  return &_impl_.results_;
}
inline const ::tensorflow::serving::InferenceResult& MultiInferenceResponse::_internal_results(int index) const {
  return _impl_.results_.Get(index);
}
inline const ::tensorflow::serving::InferenceResult& MultiInferenceResponse::results(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.MultiInferenceResponse.results)
  return _internal_results(index);
}
inline ::tensorflow::serving::InferenceResult* MultiInferenceResponse::_internal_add_results() {
  return _impl_.results_.Add();
}
inline ::tensorflow::serving::InferenceResult* MultiInferenceResponse::add_results() {
  ::tensorflow::serving::InferenceResult* _add = _internal_add_results();
  // @@protoc_insertion_point(field_add:tensorflow.serving.MultiInferenceResponse.results)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::serving::InferenceResult >&
MultiInferenceResponse::results() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.MultiInferenceResponse.results)
  return _impl_.results_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace serving
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tensorflow_5fserving_2fapis_2finference_2eproto
