// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/apis/session_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tensorflow_5fserving_2fapis_2fsession_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tensorflow_5fserving_2fapis_2fsession_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow/core/protobuf/config.pb.h"
#include "tensorflow/core/protobuf/named_tensor.pb.h"
#include "tensorflow_serving/apis/model.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tensorflow_5fserving_2fapis_2fsession_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tensorflow_5fserving_2fapis_2fsession_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tensorflow_5fserving_2fapis_2fsession_5fservice_2eproto;
namespace tensorflow {
namespace serving {
class SessionRunRequest;
struct SessionRunRequestDefaultTypeInternal;
extern SessionRunRequestDefaultTypeInternal _SessionRunRequest_default_instance_;
class SessionRunResponse;
struct SessionRunResponseDefaultTypeInternal;
extern SessionRunResponseDefaultTypeInternal _SessionRunResponse_default_instance_;
}  // namespace serving
}  // namespace tensorflow
PROTOBUF_NAMESPACE_OPEN
template<> ::tensorflow::serving::SessionRunRequest* Arena::CreateMaybeMessage<::tensorflow::serving::SessionRunRequest>(Arena*);
template<> ::tensorflow::serving::SessionRunResponse* Arena::CreateMaybeMessage<::tensorflow::serving::SessionRunResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tensorflow {
namespace serving {

// ===================================================================

class SessionRunRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.SessionRunRequest) */ {
 public:
  inline SessionRunRequest() : SessionRunRequest(nullptr) {}
  ~SessionRunRequest() override;
  explicit PROTOBUF_CONSTEXPR SessionRunRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SessionRunRequest(const SessionRunRequest& from);
  SessionRunRequest(SessionRunRequest&& from) noexcept
    : SessionRunRequest() {
    *this = ::std::move(from);
  }

  inline SessionRunRequest& operator=(const SessionRunRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionRunRequest& operator=(SessionRunRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SessionRunRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SessionRunRequest* internal_default_instance() {
    return reinterpret_cast<const SessionRunRequest*>(
               &_SessionRunRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SessionRunRequest& a, SessionRunRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SessionRunRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionRunRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SessionRunRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SessionRunRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SessionRunRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SessionRunRequest& from) {
    SessionRunRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SessionRunRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tensorflow.serving.SessionRunRequest";
  }
  protected:
  explicit SessionRunRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFeedFieldNumber = 2,
    kFetchFieldNumber = 3,
    kTargetFieldNumber = 4,
    kModelSpecFieldNumber = 1,
    kOptionsFieldNumber = 5,
    kTensorNameIsAliasFieldNumber = 6,
  };
  // repeated .tensorflow.NamedTensorProto feed = 2;
  int feed_size() const;
  private:
  int _internal_feed_size() const;
  public:
  void clear_feed();
  ::tensorflow::NamedTensorProto* mutable_feed(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto >*
      mutable_feed();
  private:
  const ::tensorflow::NamedTensorProto& _internal_feed(int index) const;
  ::tensorflow::NamedTensorProto* _internal_add_feed();
  public:
  const ::tensorflow::NamedTensorProto& feed(int index) const;
  ::tensorflow::NamedTensorProto* add_feed();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto >&
      feed() const;

  // repeated string fetch = 3;
  int fetch_size() const;
  private:
  int _internal_fetch_size() const;
  public:
  void clear_fetch();
  const std::string& fetch(int index) const;
  std::string* mutable_fetch(int index);
  void set_fetch(int index, const std::string& value);
  void set_fetch(int index, std::string&& value);
  void set_fetch(int index, const char* value);
  void set_fetch(int index, const char* value, size_t size);
  std::string* add_fetch();
  void add_fetch(const std::string& value);
  void add_fetch(std::string&& value);
  void add_fetch(const char* value);
  void add_fetch(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& fetch() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_fetch();
  private:
  const std::string& _internal_fetch(int index) const;
  std::string* _internal_add_fetch();
  public:

  // repeated string target = 4;
  int target_size() const;
  private:
  int _internal_target_size() const;
  public:
  void clear_target();
  const std::string& target(int index) const;
  std::string* mutable_target(int index);
  void set_target(int index, const std::string& value);
  void set_target(int index, std::string&& value);
  void set_target(int index, const char* value);
  void set_target(int index, const char* value, size_t size);
  std::string* add_target();
  void add_target(const std::string& value);
  void add_target(std::string&& value);
  void add_target(const char* value);
  void add_target(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& target() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_target();
  private:
  const std::string& _internal_target(int index) const;
  std::string* _internal_add_target();
  public:

  // .tensorflow.serving.ModelSpec model_spec = 1;
  bool has_model_spec() const;
  private:
  bool _internal_has_model_spec() const;
  public:
  void clear_model_spec();
  const ::tensorflow::serving::ModelSpec& model_spec() const;
  PROTOBUF_NODISCARD ::tensorflow::serving::ModelSpec* release_model_spec();
  ::tensorflow::serving::ModelSpec* mutable_model_spec();
  void set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec);
  private:
  const ::tensorflow::serving::ModelSpec& _internal_model_spec() const;
  ::tensorflow::serving::ModelSpec* _internal_mutable_model_spec();
  public:
  void unsafe_arena_set_allocated_model_spec(
      ::tensorflow::serving::ModelSpec* model_spec);
  ::tensorflow::serving::ModelSpec* unsafe_arena_release_model_spec();

  // .tensorflow.RunOptions options = 5;
  bool has_options() const;
  private:
  bool _internal_has_options() const;
  public:
  void clear_options();
  const ::tensorflow::RunOptions& options() const;
  PROTOBUF_NODISCARD ::tensorflow::RunOptions* release_options();
  ::tensorflow::RunOptions* mutable_options();
  void set_allocated_options(::tensorflow::RunOptions* options);
  private:
  const ::tensorflow::RunOptions& _internal_options() const;
  ::tensorflow::RunOptions* _internal_mutable_options();
  public:
  void unsafe_arena_set_allocated_options(
      ::tensorflow::RunOptions* options);
  ::tensorflow::RunOptions* unsafe_arena_release_options();

  // bool tensor_name_is_alias = 6;
  void clear_tensor_name_is_alias();
  bool tensor_name_is_alias() const;
  void set_tensor_name_is_alias(bool value);
  private:
  bool _internal_tensor_name_is_alias() const;
  void _internal_set_tensor_name_is_alias(bool value);
  public:

  // @@protoc_insertion_point(class_scope:tensorflow.serving.SessionRunRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto > feed_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> fetch_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> target_;
    ::tensorflow::serving::ModelSpec* model_spec_;
    ::tensorflow::RunOptions* options_;
    bool tensor_name_is_alias_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tensorflow_5fserving_2fapis_2fsession_5fservice_2eproto;
};
// -------------------------------------------------------------------

class SessionRunResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.SessionRunResponse) */ {
 public:
  inline SessionRunResponse() : SessionRunResponse(nullptr) {}
  ~SessionRunResponse() override;
  explicit PROTOBUF_CONSTEXPR SessionRunResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SessionRunResponse(const SessionRunResponse& from);
  SessionRunResponse(SessionRunResponse&& from) noexcept
    : SessionRunResponse() {
    *this = ::std::move(from);
  }

  inline SessionRunResponse& operator=(const SessionRunResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SessionRunResponse& operator=(SessionRunResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SessionRunResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SessionRunResponse* internal_default_instance() {
    return reinterpret_cast<const SessionRunResponse*>(
               &_SessionRunResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SessionRunResponse& a, SessionRunResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SessionRunResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SessionRunResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SessionRunResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SessionRunResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SessionRunResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SessionRunResponse& from) {
    SessionRunResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SessionRunResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tensorflow.serving.SessionRunResponse";
  }
  protected:
  explicit SessionRunResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTensorFieldNumber = 1,
    kMetadataFieldNumber = 2,
    kModelSpecFieldNumber = 3,
  };
  // repeated .tensorflow.NamedTensorProto tensor = 1;
  int tensor_size() const;
  private:
  int _internal_tensor_size() const;
  public:
  void clear_tensor();
  ::tensorflow::NamedTensorProto* mutable_tensor(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto >*
      mutable_tensor();
  private:
  const ::tensorflow::NamedTensorProto& _internal_tensor(int index) const;
  ::tensorflow::NamedTensorProto* _internal_add_tensor();
  public:
  const ::tensorflow::NamedTensorProto& tensor(int index) const;
  ::tensorflow::NamedTensorProto* add_tensor();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto >&
      tensor() const;

  // .tensorflow.RunMetadata metadata = 2;
  bool has_metadata() const;
  private:
  bool _internal_has_metadata() const;
  public:
  void clear_metadata();
  const ::tensorflow::RunMetadata& metadata() const;
  PROTOBUF_NODISCARD ::tensorflow::RunMetadata* release_metadata();
  ::tensorflow::RunMetadata* mutable_metadata();
  void set_allocated_metadata(::tensorflow::RunMetadata* metadata);
  private:
  const ::tensorflow::RunMetadata& _internal_metadata() const;
  ::tensorflow::RunMetadata* _internal_mutable_metadata();
  public:
  void unsafe_arena_set_allocated_metadata(
      ::tensorflow::RunMetadata* metadata);
  ::tensorflow::RunMetadata* unsafe_arena_release_metadata();

  // .tensorflow.serving.ModelSpec model_spec = 3;
  bool has_model_spec() const;
  private:
  bool _internal_has_model_spec() const;
  public:
  void clear_model_spec();
  const ::tensorflow::serving::ModelSpec& model_spec() const;
  PROTOBUF_NODISCARD ::tensorflow::serving::ModelSpec* release_model_spec();
  ::tensorflow::serving::ModelSpec* mutable_model_spec();
  void set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec);
  private:
  const ::tensorflow::serving::ModelSpec& _internal_model_spec() const;
  ::tensorflow::serving::ModelSpec* _internal_mutable_model_spec();
  public:
  void unsafe_arena_set_allocated_model_spec(
      ::tensorflow::serving::ModelSpec* model_spec);
  ::tensorflow::serving::ModelSpec* unsafe_arena_release_model_spec();

  // @@protoc_insertion_point(class_scope:tensorflow.serving.SessionRunResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto > tensor_;
    ::tensorflow::RunMetadata* metadata_;
    ::tensorflow::serving::ModelSpec* model_spec_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_tensorflow_5fserving_2fapis_2fsession_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SessionRunRequest

// .tensorflow.serving.ModelSpec model_spec = 1;
inline bool SessionRunRequest::_internal_has_model_spec() const {
  return this != internal_default_instance() && _impl_.model_spec_ != nullptr;
}
inline bool SessionRunRequest::has_model_spec() const {
  return _internal_has_model_spec();
}
inline const ::tensorflow::serving::ModelSpec& SessionRunRequest::_internal_model_spec() const {
  const ::tensorflow::serving::ModelSpec* p = _impl_.model_spec_;
  return p != nullptr ? *p : reinterpret_cast<const ::tensorflow::serving::ModelSpec&>(
      ::tensorflow::serving::_ModelSpec_default_instance_);
}
inline const ::tensorflow::serving::ModelSpec& SessionRunRequest::model_spec() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SessionRunRequest.model_spec)
  return _internal_model_spec();
}
inline void SessionRunRequest::unsafe_arena_set_allocated_model_spec(
    ::tensorflow::serving::ModelSpec* model_spec) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_spec_);
  }
  _impl_.model_spec_ = model_spec;
  if (model_spec) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.SessionRunRequest.model_spec)
}
inline ::tensorflow::serving::ModelSpec* SessionRunRequest::release_model_spec() {
  
  ::tensorflow::serving::ModelSpec* temp = _impl_.model_spec_;
  _impl_.model_spec_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tensorflow::serving::ModelSpec* SessionRunRequest::unsafe_arena_release_model_spec() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.SessionRunRequest.model_spec)
  
  ::tensorflow::serving::ModelSpec* temp = _impl_.model_spec_;
  _impl_.model_spec_ = nullptr;
  return temp;
}
inline ::tensorflow::serving::ModelSpec* SessionRunRequest::_internal_mutable_model_spec() {
  
  if (_impl_.model_spec_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::serving::ModelSpec>(GetArenaForAllocation());
    _impl_.model_spec_ = p;
  }
  return _impl_.model_spec_;
}
inline ::tensorflow::serving::ModelSpec* SessionRunRequest::mutable_model_spec() {
  ::tensorflow::serving::ModelSpec* _msg = _internal_mutable_model_spec();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.SessionRunRequest.model_spec)
  return _msg;
}
inline void SessionRunRequest::set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_spec_);
  }
  if (model_spec) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(model_spec));
    if (message_arena != submessage_arena) {
      model_spec = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, model_spec, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.model_spec_ = model_spec;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.SessionRunRequest.model_spec)
}

// repeated .tensorflow.NamedTensorProto feed = 2;
inline int SessionRunRequest::_internal_feed_size() const {
  return _impl_.feed_.size();
}
inline int SessionRunRequest::feed_size() const {
  return _internal_feed_size();
}
inline ::tensorflow::NamedTensorProto* SessionRunRequest::mutable_feed(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.SessionRunRequest.feed)
  return _impl_.feed_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto >*
SessionRunRequest::mutable_feed() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.SessionRunRequest.feed)
  return &_impl_.feed_;
}
inline const ::tensorflow::NamedTensorProto& SessionRunRequest::_internal_feed(int index) const {
  return _impl_.feed_.Get(index);
}
inline const ::tensorflow::NamedTensorProto& SessionRunRequest::feed(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SessionRunRequest.feed)
  return _internal_feed(index);
}
inline ::tensorflow::NamedTensorProto* SessionRunRequest::_internal_add_feed() {
  return _impl_.feed_.Add();
}
inline ::tensorflow::NamedTensorProto* SessionRunRequest::add_feed() {
  ::tensorflow::NamedTensorProto* _add = _internal_add_feed();
  // @@protoc_insertion_point(field_add:tensorflow.serving.SessionRunRequest.feed)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto >&
SessionRunRequest::feed() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.SessionRunRequest.feed)
  return _impl_.feed_;
}

// repeated string fetch = 3;
inline int SessionRunRequest::_internal_fetch_size() const {
  return _impl_.fetch_.size();
}
inline int SessionRunRequest::fetch_size() const {
  return _internal_fetch_size();
}
inline void SessionRunRequest::clear_fetch() {
  _impl_.fetch_.Clear();
}
inline std::string* SessionRunRequest::add_fetch() {
  std::string* _s = _internal_add_fetch();
  // @@protoc_insertion_point(field_add_mutable:tensorflow.serving.SessionRunRequest.fetch)
  return _s;
}
inline const std::string& SessionRunRequest::_internal_fetch(int index) const {
  return _impl_.fetch_.Get(index);
}
inline const std::string& SessionRunRequest::fetch(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SessionRunRequest.fetch)
  return _internal_fetch(index);
}
inline std::string* SessionRunRequest::mutable_fetch(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.SessionRunRequest.fetch)
  return _impl_.fetch_.Mutable(index);
}
inline void SessionRunRequest::set_fetch(int index, const std::string& value) {
  _impl_.fetch_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:tensorflow.serving.SessionRunRequest.fetch)
}
inline void SessionRunRequest::set_fetch(int index, std::string&& value) {
  _impl_.fetch_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:tensorflow.serving.SessionRunRequest.fetch)
}
inline void SessionRunRequest::set_fetch(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.fetch_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tensorflow.serving.SessionRunRequest.fetch)
}
inline void SessionRunRequest::set_fetch(int index, const char* value, size_t size) {
  _impl_.fetch_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tensorflow.serving.SessionRunRequest.fetch)
}
inline std::string* SessionRunRequest::_internal_add_fetch() {
  return _impl_.fetch_.Add();
}
inline void SessionRunRequest::add_fetch(const std::string& value) {
  _impl_.fetch_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tensorflow.serving.SessionRunRequest.fetch)
}
inline void SessionRunRequest::add_fetch(std::string&& value) {
  _impl_.fetch_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tensorflow.serving.SessionRunRequest.fetch)
}
inline void SessionRunRequest::add_fetch(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.fetch_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tensorflow.serving.SessionRunRequest.fetch)
}
inline void SessionRunRequest::add_fetch(const char* value, size_t size) {
  _impl_.fetch_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tensorflow.serving.SessionRunRequest.fetch)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
SessionRunRequest::fetch() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.SessionRunRequest.fetch)
  return _impl_.fetch_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
SessionRunRequest::mutable_fetch() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.SessionRunRequest.fetch)
  return &_impl_.fetch_;
}

// repeated string target = 4;
inline int SessionRunRequest::_internal_target_size() const {
  return _impl_.target_.size();
}
inline int SessionRunRequest::target_size() const {
  return _internal_target_size();
}
inline void SessionRunRequest::clear_target() {
  _impl_.target_.Clear();
}
inline std::string* SessionRunRequest::add_target() {
  std::string* _s = _internal_add_target();
  // @@protoc_insertion_point(field_add_mutable:tensorflow.serving.SessionRunRequest.target)
  return _s;
}
inline const std::string& SessionRunRequest::_internal_target(int index) const {
  return _impl_.target_.Get(index);
}
inline const std::string& SessionRunRequest::target(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SessionRunRequest.target)
  return _internal_target(index);
}
inline std::string* SessionRunRequest::mutable_target(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.SessionRunRequest.target)
  return _impl_.target_.Mutable(index);
}
inline void SessionRunRequest::set_target(int index, const std::string& value) {
  _impl_.target_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:tensorflow.serving.SessionRunRequest.target)
}
inline void SessionRunRequest::set_target(int index, std::string&& value) {
  _impl_.target_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:tensorflow.serving.SessionRunRequest.target)
}
inline void SessionRunRequest::set_target(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.target_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tensorflow.serving.SessionRunRequest.target)
}
inline void SessionRunRequest::set_target(int index, const char* value, size_t size) {
  _impl_.target_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tensorflow.serving.SessionRunRequest.target)
}
inline std::string* SessionRunRequest::_internal_add_target() {
  return _impl_.target_.Add();
}
inline void SessionRunRequest::add_target(const std::string& value) {
  _impl_.target_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tensorflow.serving.SessionRunRequest.target)
}
inline void SessionRunRequest::add_target(std::string&& value) {
  _impl_.target_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tensorflow.serving.SessionRunRequest.target)
}
inline void SessionRunRequest::add_target(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.target_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tensorflow.serving.SessionRunRequest.target)
}
inline void SessionRunRequest::add_target(const char* value, size_t size) {
  _impl_.target_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tensorflow.serving.SessionRunRequest.target)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
SessionRunRequest::target() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.SessionRunRequest.target)
  return _impl_.target_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
SessionRunRequest::mutable_target() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.SessionRunRequest.target)
  return &_impl_.target_;
}

// bool tensor_name_is_alias = 6;
inline void SessionRunRequest::clear_tensor_name_is_alias() {
  _impl_.tensor_name_is_alias_ = false;
}
inline bool SessionRunRequest::_internal_tensor_name_is_alias() const {
  return _impl_.tensor_name_is_alias_;
}
inline bool SessionRunRequest::tensor_name_is_alias() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SessionRunRequest.tensor_name_is_alias)
  return _internal_tensor_name_is_alias();
}
inline void SessionRunRequest::_internal_set_tensor_name_is_alias(bool value) {
  
  _impl_.tensor_name_is_alias_ = value;
}
inline void SessionRunRequest::set_tensor_name_is_alias(bool value) {
  _internal_set_tensor_name_is_alias(value);
  // @@protoc_insertion_point(field_set:tensorflow.serving.SessionRunRequest.tensor_name_is_alias)
}

// .tensorflow.RunOptions options = 5;
inline bool SessionRunRequest::_internal_has_options() const {
  return this != internal_default_instance() && _impl_.options_ != nullptr;
}
inline bool SessionRunRequest::has_options() const {
  return _internal_has_options();
}
inline const ::tensorflow::RunOptions& SessionRunRequest::_internal_options() const {
  const ::tensorflow::RunOptions* p = _impl_.options_;
  return p != nullptr ? *p : reinterpret_cast<const ::tensorflow::RunOptions&>(
      ::tensorflow::_RunOptions_default_instance_);
}
inline const ::tensorflow::RunOptions& SessionRunRequest::options() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SessionRunRequest.options)
  return _internal_options();
}
inline void SessionRunRequest::unsafe_arena_set_allocated_options(
    ::tensorflow::RunOptions* options) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.options_);
  }
  _impl_.options_ = options;
  if (options) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.SessionRunRequest.options)
}
inline ::tensorflow::RunOptions* SessionRunRequest::release_options() {
  
  ::tensorflow::RunOptions* temp = _impl_.options_;
  _impl_.options_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tensorflow::RunOptions* SessionRunRequest::unsafe_arena_release_options() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.SessionRunRequest.options)
  
  ::tensorflow::RunOptions* temp = _impl_.options_;
  _impl_.options_ = nullptr;
  return temp;
}
inline ::tensorflow::RunOptions* SessionRunRequest::_internal_mutable_options() {
  
  if (_impl_.options_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::RunOptions>(GetArenaForAllocation());
    _impl_.options_ = p;
  }
  return _impl_.options_;
}
inline ::tensorflow::RunOptions* SessionRunRequest::mutable_options() {
  ::tensorflow::RunOptions* _msg = _internal_mutable_options();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.SessionRunRequest.options)
  return _msg;
}
inline void SessionRunRequest::set_allocated_options(::tensorflow::RunOptions* options) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.options_);
  }
  if (options) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(options));
    if (message_arena != submessage_arena) {
      options = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, options, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.options_ = options;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.SessionRunRequest.options)
}

// -------------------------------------------------------------------

// SessionRunResponse

// .tensorflow.serving.ModelSpec model_spec = 3;
inline bool SessionRunResponse::_internal_has_model_spec() const {
  return this != internal_default_instance() && _impl_.model_spec_ != nullptr;
}
inline bool SessionRunResponse::has_model_spec() const {
  return _internal_has_model_spec();
}
inline const ::tensorflow::serving::ModelSpec& SessionRunResponse::_internal_model_spec() const {
  const ::tensorflow::serving::ModelSpec* p = _impl_.model_spec_;
  return p != nullptr ? *p : reinterpret_cast<const ::tensorflow::serving::ModelSpec&>(
      ::tensorflow::serving::_ModelSpec_default_instance_);
}
inline const ::tensorflow::serving::ModelSpec& SessionRunResponse::model_spec() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SessionRunResponse.model_spec)
  return _internal_model_spec();
}
inline void SessionRunResponse::unsafe_arena_set_allocated_model_spec(
    ::tensorflow::serving::ModelSpec* model_spec) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_spec_);
  }
  _impl_.model_spec_ = model_spec;
  if (model_spec) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.SessionRunResponse.model_spec)
}
inline ::tensorflow::serving::ModelSpec* SessionRunResponse::release_model_spec() {
  
  ::tensorflow::serving::ModelSpec* temp = _impl_.model_spec_;
  _impl_.model_spec_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tensorflow::serving::ModelSpec* SessionRunResponse::unsafe_arena_release_model_spec() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.SessionRunResponse.model_spec)
  
  ::tensorflow::serving::ModelSpec* temp = _impl_.model_spec_;
  _impl_.model_spec_ = nullptr;
  return temp;
}
inline ::tensorflow::serving::ModelSpec* SessionRunResponse::_internal_mutable_model_spec() {
  
  if (_impl_.model_spec_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::serving::ModelSpec>(GetArenaForAllocation());
    _impl_.model_spec_ = p;
  }
  return _impl_.model_spec_;
}
inline ::tensorflow::serving::ModelSpec* SessionRunResponse::mutable_model_spec() {
  ::tensorflow::serving::ModelSpec* _msg = _internal_mutable_model_spec();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.SessionRunResponse.model_spec)
  return _msg;
}
inline void SessionRunResponse::set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.model_spec_);
  }
  if (model_spec) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(model_spec));
    if (message_arena != submessage_arena) {
      model_spec = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, model_spec, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.model_spec_ = model_spec;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.SessionRunResponse.model_spec)
}

// repeated .tensorflow.NamedTensorProto tensor = 1;
inline int SessionRunResponse::_internal_tensor_size() const {
  return _impl_.tensor_.size();
}
inline int SessionRunResponse::tensor_size() const {
  return _internal_tensor_size();
}
inline ::tensorflow::NamedTensorProto* SessionRunResponse::mutable_tensor(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.SessionRunResponse.tensor)
  return _impl_.tensor_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto >*
SessionRunResponse::mutable_tensor() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.SessionRunResponse.tensor)
  return &_impl_.tensor_;
}
inline const ::tensorflow::NamedTensorProto& SessionRunResponse::_internal_tensor(int index) const {
  return _impl_.tensor_.Get(index);
}
inline const ::tensorflow::NamedTensorProto& SessionRunResponse::tensor(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SessionRunResponse.tensor)
  return _internal_tensor(index);
}
inline ::tensorflow::NamedTensorProto* SessionRunResponse::_internal_add_tensor() {
  return _impl_.tensor_.Add();
}
inline ::tensorflow::NamedTensorProto* SessionRunResponse::add_tensor() {
  ::tensorflow::NamedTensorProto* _add = _internal_add_tensor();
  // @@protoc_insertion_point(field_add:tensorflow.serving.SessionRunResponse.tensor)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::tensorflow::NamedTensorProto >&
SessionRunResponse::tensor() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.SessionRunResponse.tensor)
  return _impl_.tensor_;
}

// .tensorflow.RunMetadata metadata = 2;
inline bool SessionRunResponse::_internal_has_metadata() const {
  return this != internal_default_instance() && _impl_.metadata_ != nullptr;
}
inline bool SessionRunResponse::has_metadata() const {
  return _internal_has_metadata();
}
inline const ::tensorflow::RunMetadata& SessionRunResponse::_internal_metadata() const {
  const ::tensorflow::RunMetadata* p = _impl_.metadata_;
  return p != nullptr ? *p : reinterpret_cast<const ::tensorflow::RunMetadata&>(
      ::tensorflow::_RunMetadata_default_instance_);
}
inline const ::tensorflow::RunMetadata& SessionRunResponse::metadata() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.SessionRunResponse.metadata)
  return _internal_metadata();
}
inline void SessionRunResponse::unsafe_arena_set_allocated_metadata(
    ::tensorflow::RunMetadata* metadata) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.metadata_);
  }
  _impl_.metadata_ = metadata;
  if (metadata) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.SessionRunResponse.metadata)
}
inline ::tensorflow::RunMetadata* SessionRunResponse::release_metadata() {
  
  ::tensorflow::RunMetadata* temp = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::tensorflow::RunMetadata* SessionRunResponse::unsafe_arena_release_metadata() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.SessionRunResponse.metadata)
  
  ::tensorflow::RunMetadata* temp = _impl_.metadata_;
  _impl_.metadata_ = nullptr;
  return temp;
}
inline ::tensorflow::RunMetadata* SessionRunResponse::_internal_mutable_metadata() {
  
  if (_impl_.metadata_ == nullptr) {
    auto* p = CreateMaybeMessage<::tensorflow::RunMetadata>(GetArenaForAllocation());
    _impl_.metadata_ = p;
  }
  return _impl_.metadata_;
}
inline ::tensorflow::RunMetadata* SessionRunResponse::mutable_metadata() {
  ::tensorflow::RunMetadata* _msg = _internal_mutable_metadata();
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.SessionRunResponse.metadata)
  return _msg;
}
inline void SessionRunResponse::set_allocated_metadata(::tensorflow::RunMetadata* metadata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.metadata_);
  }
  if (metadata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(metadata));
    if (message_arena != submessage_arena) {
      metadata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, metadata, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.metadata_ = metadata;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.SessionRunResponse.metadata)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace serving
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tensorflow_5fserving_2fapis_2fsession_5fservice_2eproto
